server:
  port: 9090
  max-http-header-size: 102400
spring:
  application:
    name: sibo-mall-admin
  datasource:
    driver-class-name:
    url: jdbc:mysql://localhost:3306/sibo-mall?useUnicode=true&useSSL=true&autoReconnect=true&failOverReadOnly=false&characterEncoding=gbk
    username: root
    password: 123456
#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cn.ouayngfan.mall.sibo.admin.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'

#eureka:
#  client:
#    #从eureka服务器获取注册表信息的频率（s） 30
#    registry-fetch-interval-seconds: 5
#    #更新实例信息的变化到Eureka服务端的间隔时间，（s） 30
#    instance-info-replication-interval-seconds: 5
#    #询问Eureka Server信息变化的时间间隔（s），默认为300秒
#    eureka-service-url-poll-interval-seconds: 5
#    service-url:
#      defaultZone: http://127.0.0.1:9001/eureka/
#security:
#  oauth2:
#    client:
#      # 项目启动时从认证服务器获取签名的key时需要用到的签名信息
#      client-id: 04e6337ae6c7435d8b2eda995878fe0e
#      client-secret: 04e6337ae6c7435d8b2eda995878fe0e
#    resource:
#      jwt:
#        # 项目启动时从认证服务器获取签名的key
#        key-uri: http://sibo.ouyangfan.cn:7003/sso/oauth/token_key
sso:
  #获取授权码的地址
  authorize-url: http://sso.ouyangfan.cn:9999/oauth/authorize
  #获取token的地址
  token-url: http://sso.ouyangfan.cn:9999/oauth/token
  #admin的回调函数地址
  callback-url: http://admin.ouyangfan.cn:9090/oauth/callback
  #clientId
  client-id: 04e6337ae6c7435d8b2eda995878fe0e
  #clientSecret
  client-secret: 04e6337ae6c7435d8b2eda995878fe0e
  scope: admin
  # 带着token要跳转的页面
  front-page: http://127.0.0.1:8001/#/login

