server:
  port: 7003
spring:
  application:
    name: sibo-mall-gateway
  cloud:
    gateway:
      routes:
        - id: admin_routh_index  # 路由id  唯一
          uri: http://127.0.0.1:9090/  # 服务路由地址
          predicates:
            - Path= /idnex.html            #断言，路径相匹配的进行路由
        - id: admin_routh_oauth_callback  # 路由id  唯一
          uri: http://127.0.0.1:9090/  # 服务路由地址
          predicates:
            - Path= /oauth/callback      #断言，路径相匹配的进行路由
security:
  oauth2:
    client:
      # 项目启动时从认证服务器获取签名的key时需要用到的签名信息
      client-id: 04e6337ae6c7435d8b2eda995878fe0e
      client-secret: 04e6337ae6c7435d8b2eda995878fe0e
    resource:
      jwt:
        # 项目启动时从认证服务器获取签名的key
        key-uri: http://127.0.0.1:9999/oauth/token_key
