server:
  port: 7003
spring:
  application:
    name: sibo-mall-gateway
zuul:
  routes:
    admin:
      path: /admin/**
      serviceId: SIBO-MALL-ADMIN
    sso:
      path: /sso/**
      serviceId: SIBO-MALL-SECURITY
  sensitive-headers:
security:
  oauth2:
    client:
      # 项目启动时从认证服务器获取签名的key时需要用到的签名信息
      client-id: 04e6337ae6c7435d8b2eda995878fe0e
      client-secret: 04e6337ae6c7435d8b2eda995878fe0e
    resource:
      jwt:
        # 项目启动时从认证服务器获取签名的key
        key-uri: http://sso.ouyangfan.cn:9999/oauth/token_key
eureka:
  client:
    #从eureka服务器获取注册表信息的频率（s） 30
    registry-fetch-interval-seconds: 5
    #更新实例信息的变化到Eureka服务端的间隔时间，（s） 30
    instance-info-replication-interval-seconds: 5
    #询问Eureka Server信息变化的时间间隔（s），默认为300秒
    eureka-service-url-poll-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:9001/eureka/
